language: node_js
sudo: false
node_js:
- 4.4.7
- node
env:
  global:
  - NODE_ENV=test
before_install:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
cache:
- directories:
  - ./node_modules
services:
- rabbitmq
script:
  - npm run test
notifications:
  email: false
  slack:
    on_success: change
    on_failure: change
    rooms:
    - secure: Q8OJnQnA0a7pbVBOxwjOGhrwDXPkSGODndxFdeNI3Pfi2qgV+8AE/vJvKRlOw4Dv5BshdCD8ObAd4rU+bwjpRNt81fL7taIssOZ8YyeE34FAqo/ykLUXdIliuVWoCuT0H+OWKkSAhp6ltCG4rXOAUfuowUfb0d031YRWiu22jiI=
