version: '2'
services:
  cream:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      - NODE_ENV=test
    command: npm test
    ports:
     - "80:80"
    links:
      - rabbit
    environment:
      - RABBITMQ_HOSTNAME=rabbit

  rabbit:
    build:
      context: .
      dockerfile: Dockerfile.rabbit
    ports:
     - "5672:5672"
     - "15672:15672"
